services:
    maxine:
      container_name: maxine
      image: ghcr.io/sasharyder/maxine:latest
      restart: always
      volumes:
        - "./data:/data"
      environment:
        - TZ=Europe/London
        - DISCORD_TOKEN=123
        - NICKNAME=Maxine
        - STATUS=Hello!
        - AZURE_STORAGE_CONNECTION_STRING= #Optional
        - EMBED_URL= #Optional
        - EMBED_SERVER_PORT=12345 #Optional
        - DEEPL_API_KEY=1234 #Optional
        - CHATGPT_API_KEY=1234 #Optional
        - CHATGPT_ASSISTANT_ID=1234 #Optional