version: '3.7'
services:
    daisy-discord-bot:
      container_name: daisy-discord-bot
      build: .
      restart: always
      # ports:
      #   - 8075:8075 Only used for debugging locally.
      volumes:
        - "./data:/data"
      environment:
        - TZ=Europe/London
        - DISCORD_TOKEN=123
        - NICKNAME=Daisy
        - STATUS=Daisy Bot!
        - AZURE_STORAGE_CONNECTION_STRING=
        - EMBED_URL=
        - ENABLE_INSPECTOR=false
        - EMBED_SERVER_PORT=12345
        - DEEPL_API_KEY=1234
        - CHATGPT_API_KEY=1234